openapi: '3.0.3'
info:
  title: KeyWarden
  version: '0.10.2'
servers:
  - url: https://api.server.test/v1
tags:
  - name: 'auth'
  - name: 'admin'
  - name: 'profile'
  - name: 'passwordResetToken'

paths:
  /api/auth/signup:
    post:
      tags:
        - 'auth'
      summary: 'Register new user'
      description: 'Check if there is an existing user and save a new one to database'
      operationId: signup
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SignupForm'
      responses:
        '201':
          $ref: '#/components/responses/OK'
        '400':
          description: 'Username already taken!'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiError'

  /api/auth/signin:
    post:
      tags:
        - 'auth'
      summary: 'User login'
      description: 'Authenticate {username, password} and generate a JWT'
      operationId: signin
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SigninForm'
      responses:
        '200':
          description: 'Authenticated successfully!'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/JWTResponse'
        '401':
          $ref: '#/components/responses/Unauthorized'

  /api/auth/forgotpassword:
    post:
      tags:
        - 'passwordResetToken'
      summary: 'Send user an email with url/{token} to update his forgotten password'
      description: 'Access enabled to any role'
      operationId: emailPasswordResetToken
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Username'
      responses:
        '200':
          $ref: '#/components/responses/OK'
        '404':
          $ref: '#/components/responses/NotFound'
    
  /api/auth/forgotpassword/{token}:  
    patch:
      tags:
        - 'passwordResetToken'
      summary: 'Reset user password'
      description: 'Access enabled to any role'
      operationId: resetUserPassword
      parameters:
        - name: token
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PasswordMatch'
      responses:
        '200':
          $ref: '#/components/responses/OK'
        '400':
          $ref: '#/components/responses/BadRequest'
        '404':
          $ref: '#/components/responses/NotFound'

  /api/auth/profile:
    get:
      tags:
        - 'profile'
      security:
        - bearerAuth: []
      summary: 'User Profile Content'
      description: 'Access enabled only to Authenticated User [Any Role]'
      operationId: profileContent
      responses:
        '200':
          description: 'User Profile Content received successfuly!'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Profile'
        '401':
          description: 'You are not logged in!'
    patch:
      tags:
        - 'profile'
      security:
        - bearerAuth: []
      summary: 'Alter User password'
      description: 'Access enabled only to Authenticated User [Any Role]'
      operationId: alterUserPassword
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PasswordUpdateForm'
      responses:
        '200':
          description: 'User Password updated successfully!'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OkMessage'
        '400':
          description: 'Invalid Password Form!'
        '401':
          description: 'You are not logged in!'

  /api/auth/admin:
    get:
      tags:
        - 'admin'
      security:
        - bearerAuth: []
      summary: 'List of Users registrated'
      description: 'Access enabled only to Admin'
      operationId: getAllUsers
      parameters:
        - name: username
          in: query
          required: false
          description: 'Searches by part of email string'
          schema:
            type: string
        - name: role
          in: query
          required: false
          description: 'Searches by role'
          schema:
            $ref: '#/components/schemas/EnumRole'
      responses:
        '200':
          description: 'List of Users retreived successfuly!'
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/UserInfo'
        '401':
          description: 'Unauthorized!'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiError'
        '403':
          description: 'Forbidden!'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiError'
    patch:
      tags:
        - 'admin'
      security:
        - bearerAuth: []
      summary: 'Alter User Role'
      description: 'Access enabled only to Admin'
      operationId: alterUserRole
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AlterUserRolesForm'
      responses:
        '200':
          description: 'Patched User Roles successfully!'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OkMessage'
        '401':
          description: 'Unauthorized!'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiError'
        '403':
          description: 'Forbidden!'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiError'
        '404':
          description: 'User not Found!'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiError'

components:
  schemas:
    ApiError:
      type: object
      required:
        - timestamp
        - message
      properties:
        timestamp:
          type: string
          format: date-time
        message:
          type: string
          example: 'username must be have email format'
        fieldErrors:
          type: array
          items:
            type: string
            example: 'username'
    AuthenticationError:
      type: object
      required:
        - message
      properties:
        message:
          type: string
          example: 'Full authentication is required to access this resource'
    OkMessage:
      type: object
      required:
        - 'body'
      properties:
        body:
          type: string
          example: 'Success!'

    SignupForm:
      type: object
      required:
        - 'username'
        - 'password'
      properties:
        username:
          $ref: '#/components/schemas/Username'
        password:
          $ref: '#/components/schemas/Password'
        role:
          $ref: '#/components/schemas/EnumRole'
    SigninForm:
      type: object
      required:
        - 'username'
        - 'password'
      properties:
        username:
          $ref: '#/components/schemas/Username'
        password:
          $ref: '#/components/schemas/Password'
    Username:
      type: string
      format: email
      description: 'User e-mail for contact and to redefine lost password [UNIQUE]'
      example: 'example@example.com'
      minLength: 3
      maxLength: 50
    Password:
      type: string
      format: password
      description: 'User password to access account'
      example: '1234567890'
      minLength: 8
      maxLength: 120
    EnumRole:
      type: string
      enum:
        - 'ADMIN'
        - 'MANAGER'
        - 'USER'
      description: 'Client permissions. Must be hidden from Users'
    JWTResponse:
      type: object
      required:
        - 'token'
        - 'type'
      properties:
        token:
          type: string
        type:
          type: string
          default: 'Bearer'
    Profile:
      type: object
      properties:
        username:
          $ref: '#/components/schemas/Username'
    AlterUserRolesForm:
      type: object
      required:
        - 'username'
        - 'roles'
      properties:
        username:
          $ref: '#/components/schemas/Username'
        roles:
          type: array
          uniqueItems: true
          minItems: 1
          items:
            $ref: '#/components/schemas/EnumRole'
    UserId:
      type: string
      format: uuid
    UserInfo:
      type: object
      required:
        - 'id'
        - 'username'
        - 'roles'
      properties:
        id:
          type: string
          format: uuid
        username:
          $ref: '#/components/schemas/Username'
        roles:
          type: array
          uniqueItems: true
          items:
            $ref: '#/components/schemas/EnumRole'
    PasswordUpdateForm:
      type: object
      required:
        - 'oldPassword'
        - 'newPasswordMatch'
      properties:
        oldPassword:
          $ref: '#/components/schemas/Password'
        newPasswordMatch:
          $ref: '#/components/schemas/PasswordMatch'
    PasswordMatch:
      type: object
      required:
        - 'password'
        - 'passwordConfirmation'
      properties:
        password:
          $ref: '#/components/schemas/Password'
        passwordConfirmation:
          $ref: '#/components/schemas/Password'

  responses:
    OK:
      description: 'Operation successfully finished!'
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/OkMessage'
    Unauthorized:
      description: 'Operation failed due to lack of authentication or authorization'
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/AuthenticationError'
    NotFound:
      description: 'Operation failed: could not find provided resource!'
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ApiError'
    BadRequest:
      description: 'Operation failed: bad provided resource!'
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ApiError'

  securitySchemes:
    bearerAuth:
      scheme: bearer
      type: http
      bearerFormat: JWT
